[package]
name = "rust_export"
version = "0.1.0"
edition = "2021"

[dependencies]
interoptopus = "0.14.0"
interoptopus_backend_csharp = "0.14.0"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
regex = "1.7.0"

[lib]
name = "rust_export"
crate-type = ["cdylib", "rlib"]